#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

require "Commands/CreateController.php";

$application = new Application();

# add our commands
$application->add(new CreateController());

$application->run();